spring:
  application:
    name: zuul
  cloud:
    config:
      discovery:
        enabled: true
        service-id: MyConfig
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
debug: true

zuul:
  routes:
    zipkin:
    sleuth-client: