server:
  port: 8081
  address: 192.168.10.10
spring:
  application:
    name: Stores
  redis:
    host: peer1
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
