server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    ip-address: 192.168.10.212
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

