server:
  port: ${SERVER_PORT:8761}
  context-path: /eureka
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:eureka}
  cloud:
    config:
      discovery:
        service-id: MyConfig
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetchRegistry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
    serviceUrl:
      defaultZone: http://${ANOTHER_EUREKA_INSTANCE_HOST:localhost}:${ANOTHER_EUREKA_INSTANCE_PORT:8761}/eureka/