version: '3.4'
services:
  zuul:
    image: ${VERSIONED_IMAGE}
    networks:
      springcloud-overlay:
        aliases:
          - zuul
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay