version: '3.4'
services:
  store:
    image: ${VERSIONED_IMAGE}
    networks:
      springcloud-overlay:
        aliases:
          - stores
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay