version: '3.4'
services:
  store:
    image: ${VERSIONED_IMAGE}
    networks:
      springcloud-overlay:
        aliases:
          - stores
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay