server:
  port: 8080
spring:
  application:
    name: Stores
  redis:
    host: peer1
  cloud:
    config:
      discovery:
        enabled: true
        service-id: MyConfig
endpoints:
  info:
    enabled: true
  enabled: true
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.10.10
debug: true


