version: '3.2'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/lisong/cloud-web:1
    networks:
      - springcloud-overlay
    ports:
      - "80:80"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
