version: '3.4'
services:
  nginx:
    image: ${VERSIONED_IMAGE}
    networks:
      springcloud-overlay:
        aliases:
          - nginx
    ports:
      - "80:80"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
