version: '3'
services:
  config:
    image: ${VERSIONED_IMAGE}
    networks:
      springcloud-overlay:
        aliases:
          - config

networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay