version: '3.4'
services:
  config:
    image: ${VERSIONED_IMAGE}
    networks:
      springcloud-overlay:
        aliases:
          - config
    deploy:
      endpoint_mode: dnsrr

networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay