eureka:
    instance:
        hostname: peer1
        client:
            serviceUrl:
              defaultZone: http://peer2/eureka/
            register-with-eureka: true
            fetch-registry: true