server:
  port: 8761
spring:
  application:
    name: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    ip-address: 192.168.10.211
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
