server:
  port: 8761
spring:
  application:
    name: peer1
eureka:
  instance:
    hostname: peer1
    metadataMap:
      instanceId: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

