version: '3.4'
services:
  store:
    image: ${VERSIONED_IMAGE}
    networks:
      springcloud-overlay:
        aliases:
          - customer
    deploy:
      mode: replicated
      replicas: 3

networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay