version: '2'
services:
  eureka-server:
    image: ${VERSIONED_IMAGE}
    env_file:
      - node.env
    container_name: 'eureka-server'
    restart: 'always'
    ports:
     - "8761:8761"
    extra_hosts:
     - "peer1:192.168.10.211"
     - "peer2:192.168.10.212"
     - "peer3:192.168.10.213"