version: '3.4'
services:
  redis:
    image: ${VERSIONED_IMAGE}
    networks:
      springcloud-overlay:
        aliases:
          - redis
    ports:
      - "6379:6379"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
